### ISSUE TITLE
MCprep 3.6.1 Update is Missing Compiled Translations

### ISSUE THREAD

**Issue by StandingPadAnimations** [Moo-Ack-Productions/MCprep#627]
### Did the issue happen after restarting Blender?

- [X] Yes, the issue indeed continued after restarting Blender

### Check known issues

- [X] I have checked known issues, and my problem is different

### What happened?

MCprep 3.6.1 is missing compiled translation files, which causes the following erorr for end users:
```
Traceback (most recent call last):
  File "/usr/share/blender/4.2/scripts/modules/addon_utils.py", line 407, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/mahid/.config/blender/4.2/scripts/addons/MCprep_addon/__init__.py", line 59, in <module>
    from . import load_modules
  File "/home/mahid/.config/blender/4.2/scripts/addons/MCprep_addon/load_modules.py", line 28, in <module>
    from . import conf
  File "/home/mahid/.config/blender/4.2/scripts/addons/MCprep_addon/conf.py", line 325, in <module>
    env = MCprepEnv()
          ^^^^^^^^^^^
  File "/home/mahid/.config/blender/4.2/scripts/addons/MCprep_addon/conf.py", line 149, in __init__
    self.languages[language.name] = gettext.translation("mcprep",
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gettext.py", line 538, in translation
    t = _translations.setdefault(key, class_(fp))
                                      ^^^^^^^^^^
  File "/usr/lib/python3.12/gettext.py", line 272, in __init__
    self._parse(fp)
  File "/usr/lib/python3.12/gettext.py", line 424, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
```
This causes the following to occur:
- Blender registers MCprep, this results in `MCprepEnv` being constructed
- `MCprepEnv`, during the initialization sequence, notices that `translations.py` doesn't exist. As such, it falls back to using the compiled MO files
- However, because the compiled MO files also do not exist, when it attempts to do this, `gettext` returns an exception 

### What steps are needed to produce the bug?

1) Update MCprep 3.6 to MCprep 3.6.1\*
2) Restart Blender
3) Enable MCprep

\*Oddly enough, this doesn't seem to happen when manually installing MCprep 3.6.1

### What version of MCprep are you using?

MCprep 3.6.1

### What version of Blender are you using?

Blender 4.2, though this has also been observed in Blender 3.3

**Comment by StandingPadAnimations** [comment]
Closing as 3.6.1 is now pulled from releases
